// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {http} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ListVideoFiles(arg1:string):Promise<Array<string>>;

export function SearchTMDB(arg1:string):Promise<string>;

export function SelectFolder(arg1:context.Context):Promise<string>;

export function StreamVideo(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
