// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListVideoFiles(arg1) {
  return window['go']['main']['App']['ListVideoFiles'](arg1);
}

export function SearchTMDB(arg1) {
  return window['go']['main']['App']['SearchTMDB'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function StreamVideo(arg1, arg2) {
  return window['go']['main']['App']['StreamVideo'](arg1, arg2);
}
