name: Build for Windows

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install frontend deps
        run: npm install
        working-directory: ./frontend

      - name: Build
        run: wails build
        env:
          PATH: ${{ github.workspace }}/go/bin:${{ env.PATH }}

      - uses: actions/upload-artifact@v4
        with:
          name: wails-windows
          path: build/bin/*.exe
